const ROW = 15;
const COLUMN = 15;
const DIRECTION = {
  HORIZONTAL: 1,
  VERTICAL: 2,
  LEFT_OBLIQUE: 3,
  RIGHT_OBLIQUE: 4
};
const RESET = 'RESET';
const SELECT = 'SELECT';
export { ROW, COLUMN, DIRECTION, RESET, SELECT };
